// Generated by CoffeeScript 1.6.2
(function() {
  var AudioPlayer, EchoNest, Event, EventManager, Graphics, init,
    __bind = function(fn, me){ return function(){ return fn.apply(me, arguments); }; },
    _this = this;

  EventManager = new EventEmitter();

  Event = {
    TrackAnalyzed: "Track Complete"
  };

  EchoNest = (function() {
    EchoNest.prototype.RemixAPISettings = {
      TRACK_ID: 'TRKCLIJ140E5FAB0E3',
      API: 'SLU8WR6N1N06GTQNB',
      URL: 'http://s3.amazonaws.com/easybakerstreetoven-en-us/remix_audio/02%20-%20Bowl.mp3'
    };

    EchoNest.prototype.remixer = null;

    EchoNest.prototype.context = null;

    EchoNest.prototype.player = null;

    EchoNest.prototype.status = document.getElementById('status-text');

    function EchoNest() {
      this.status = document.getElementById('status-text');
      this.setupElements();
      this.createContext();
      this.createRemixer();
    }

    EchoNest.prototype.setupElements = function() {};

    EchoNest.prototype.createContext = function() {
      if (typeof webkitAudioContext !== "undefined" && webkitAudioContext !== null) {
        return this.context = new webkitAudioContext();
      } else {
        return this.context = new AudioContext();
      }
    };

    EchoNest.prototype.createRemixer = function() {
      this.remixer = createJRemixer(this.context, $, this.RemixAPISettings.API);
      return this.remixTrack();
    };

    EchoNest.prototype.remixTrack = function() {
      var _this = this;

      return this.remixer.remixTrackById(this.RemixAPISettings.TRACK_ID, this.RemixAPISettings.URL, function(track, percent) {
        var remix;

        _this.track = track;
        remix = function() {
          var part;

          part = 'tatums';
          _this.remixed = track.analysis[part];
          return EventManager.emitEvent(Event.TrackAnalyzed, [_this.remixed]);
        };
        if (_this.track.status === 'ok') {
          return remix();
        }
      });
    };

    return EchoNest;

  })();

  AudioPlayer = (function() {
    AudioPlayer.prototype.context = null;

    function AudioPlayer() {
      this.checkWebAudioContext();
      this.createContext();
    }

    AudioPlayer.prototype.checkWebAudioContext = function() {
      if (window.webkitAudioContext === void 0) {
        return new Error("Sorry, this app needs advanced web audio. Your browser doesn't", +" support it. Try the latest version of Chrome");
      }
    };

    AudioPlayer.prototype.createContext = function() {
      if (typeof webkitAudioContext !== "undefined" && webkitAudioContext !== null) {
        return this.context = new webkitAudioContext();
      } else {
        return this.context = new AudioContext();
      }
    };

    AudioPlayer.prototype.playSound = function(sound) {
      this.source = this.context.createBufferSource();
      this.source.buffer = sound;
      this.source.connect(this.context.destination);
      return this.source.noteOn(0);
    };

    return AudioPlayer;

  })();

  Graphics = (function() {
    Graphics.prototype.STEP_SIZE = 1;

    Graphics.prototype.data = null;

    Graphics.prototype.width = window.innerWidth;

    Graphics.prototype.height = window.innerHeight;

    Graphics.prototype.svg = null;

    Graphics.prototype.minSize = 1;

    Graphics.prototype.maxSize = 3;

    Graphics.prototype.scaleFactor = 100;

    Graphics.prototype.audio = null;

    Graphics.prototype.next = null;

    function Graphics(data, audio) {
      this.data = data;
      this.audio = audio;
      this.onmouseover = __bind(this.onmouseover, this);
      this.audioCallback = __bind(this.audioCallback, this);
      this.createSVG();
      this.createAudio();
    }

    Graphics.prototype.audioCallback = function(e) {
      var circ;

      this.next = this.currentAudioSample.next;
      this.currentAudioSample = this.next;
      circ = $($('#nodeHolder').children()[0]).children()[this.currentElement + this.STEP_SIZE];
      this.currentElement += this.STEP_SIZE;
      d3.select(circ).attr('r', 0);
      this.audio.stop();
      return this.audio.play(0, this.next);
    };

    Graphics.prototype.createAudio = function() {
      return this.audio.addAfterPlayCallback(this.audioCallback);
    };

    Graphics.prototype.createSVG = function() {
      var getSize, getX, scale, yOffset, yWave,
        _this = this;

      this.svg = d3.select("body").append("svg").attr('id', 'nodeHolder').attr("width", this.width).attr("height", this.height).append('g');
      getSize = function(d) {
        var size;

        size = Math.min(_this.maxSize, Math.max(_this.minSize, d.confidence * _this.scaleFactor));
        return size;
      };
      scale = this.width / parseInt(this.data[0].track.audio_summary.duration);
      getX = function(d) {
        return d.start * scale;
      };
      yWave = 10;
      yOffset = 400;
      return this.svg.selectAll('g').data(this.data).enter().append('circle').attr('cx', getX).attr('cy', function(d, i) {
        return (Math.sin(i) * yWave) + yOffset;
      }).attr('fill', 'black').attr('r', getSize).on('mouseover', this.onmouseover);
    };

    Graphics.prototype.onmouseover = function(data, el, node) {
      var circle;

      circle = d3.select(d3.event.target);
      circle.attr('r', 0);
      this.currentElement = el;
      this.currentAudioSample = data;
      this.audio.stop();
      return this.audio.play(0, data);
    };

    return Graphics;

  })();

  init = function() {
    var echo;

    echo = new EchoNest();
    return EventManager.addListener(Event.TrackAnalyzed, function(trackData) {
      var gfx;

      echo.status.innerHTML = "";
      return gfx = new Graphics(trackData, echo.remixer.getPlayer());
    });
  };

  $(document).ready(function() {
    return init();
  });

}).call(this);
