// Generated by CoffeeScript 1.6.2
(function() {
  toast('src', {
    vendors: ['js/EventEmitter-4.0.3.min.js'],
    bare: true,
    httpfolder: 'js',
    release: 'js',
    debug: 'js-debug'
  });

}).call(this);
